name: Swift

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test -v
    - name: run git log
      run: git log
